import type { Words } from "@/lib/types/db";

const memoryDB: Words[] = [
    {
      id: "232",
      content: "Hello 1",
      meaning: "你好",
      familiarity: 3,
      star: false,
      correctNum: 20,
      testNum: 24,
      accuracy: 20 / 24,
    },
    {
      id: "233",
      content: "Hello 2",
      meaning: "你好",
      familiarity: 0,
      star: true,
      correctNum: 13,
      testNum: 19,
      accuracy: 13 / 19,
    },
    {
      id: "234",
      content: "Hello 3",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 30,
      testNum: 1002,
      accuracy: 30 / 1002,
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 24,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 21,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 11,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 3,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 9,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
    {
      id: "235",
      content: "Hello 4",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 40,
      testNum: 399,
      accuracy: 40 / 399,
    },
    {
      id: "236",
      content: "Hello 5",
      meaning: "你好",
      familiarity: 0,
      star: false,
      correctNum: 32,
      testNum: 40,
      accuracy: 32 / 40
    },
  ];

export default memoryDB;